# Use an appropriate base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements-test.txt .
RUN pip install -r requirements-test.txt

# Copy the rest of the application code
COPY . .

ENV PYTHONPATH=/app

# Command to run tests
CMD ["pytest"]